import Providers from "@/app/providers"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { ConfigProvider, ThemeConfig } from "antd"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const defaultTheme: ThemeConfig = {
  components: {
    Button: {
      colorPrimary: "#f68b1f",
      colorPrimaryActive: "#D7791CFF",
      colorPrimaryHover: "#D7791CFF",
      primaryShadow: "none",
    },
    Layout: {
      headerPadding: "0 12px",
      headerBg: "#fff",
      footerBg: "#fff",
      bodyBg: "#fff",
    },
    Radio: {
      colorPrimary: "#f68b1f",
      colorText: "#002d63",
    },
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AntdRegistry>
            <ConfigProvider theme={defaultTheme}>{children}</ConfigProvider>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  )
}
